name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - name: "Récupération fichier"
      - runs-on: ubuntu-latest
        container: 
          image: ghcr.io/cicd-lectures/gitpod:latest
          options: --user=root
        uses: actions/checkout@v5
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt