name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: Read README
        id: readfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./README.md
      - name: the cowsay say
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: ${{ steps.readfile.outputs.content }}