name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - name: "Récupération fichier"
        uses: actions/checkout@v5
      - run: cat README.md | cowsay # Affiche le contenu du fichier `README.md` à la base du dépôt